version: "3"
services:
  database:
    build: ./postgres-database-docker
    container_name: ddss-database
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: ddss-webapp
    command: npm start
    environment:
      DB_HOST: database
    volumes:
      - ".:/usr/src/app"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - database
